<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SEToolkit.LiveLocation</AssemblyName>
    <RootNamespace>SEToolkit.LiveLocation</RootNamespace>
    <SpaceEngineersBin64 Condition="'$(SpaceEngineersBin64)' == ''">C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64</SpaceEngineersBin64>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Sandbox.Common">
      <HintPath>$(SpaceEngineersBin64)\Sandbox.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sandbox.Game">
      <HintPath>$(SpaceEngineersBin64)\Sandbox.Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VRage">
      <HintPath>$(SpaceEngineersBin64)\VRage.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VRage.Game">
      <HintPath>$(SpaceEngineersBin64)\VRage.Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VRage.Math">
      <HintPath>$(SpaceEngineersBin64)\VRage.Math.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
